FROM python:3

ENV UID=1000
ENV GID=1000

RUN groupadd --gid ${GID} app && \
    useradd --uid ${UID} --gid ${GID} -m --home /app app

COPY . /app/dzcb
RUN chown -R ${UID}:${GID} /app/dzcb

WORKDIR /app
USER app

RUN pip install --user -e /app/dzcb pytest

ENTRYPOINT [ "/bin/bash" ]
CMD []
